/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author srikr
 */
public class AdminjPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminjPanel
     */
    public AdminjPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAdminHeading = new javax.swing.JLabel();
        jPasswordtxt = new javax.swing.JTextField();
        jLoginbtn = new javax.swing.JButton();
        jCancelbtn = new javax.swing.JButton();
        jUsernamelbl = new javax.swing.JLabel();
        jUsernametxt = new javax.swing.JTextField();
        jPasswordlbl = new javax.swing.JLabel();
        jSelectadminlbl = new javax.swing.JLabel();
        jAdminsbox = new javax.swing.JComboBox<>();
        jBackbtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jAdminHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jAdminHeading.setText("ADMIN LOGIN");

        jLoginbtn.setText("LOGIN");
        jLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginbtnActionPerformed(evt);
            }
        });

        jCancelbtn.setText("CLEAR");

        jUsernamelbl.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jUsernamelbl.setText("USERNAME");

        jPasswordlbl.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jPasswordlbl.setText("PASSWORD");

        jSelectadminlbl.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jSelectadminlbl.setText("SELECT ADMIN");

        jAdminsbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SYSTEM", "COMMUNITY", "HOSPITAL" }));
        jAdminsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminsboxActionPerformed(evt);
            }
        });

        jBackbtn.setText("BACK");
        jBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jPasswordlbl)
                        .addComponent(jPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSelectadminlbl)
                        .addComponent(jAdminsbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jAdminHeading, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jUsernametxt, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernamelbl, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCancelbtn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackbtn, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLoginbtn, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(304, 304, 304))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBackbtn, jCancelbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jAdminHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jUsernamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSelectadminlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdminsbox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLoginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBackbtn)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBackbtn, jCancelbtn});

    }// </editor-fold>//GEN-END:initComponents

    private void jAdminsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminsboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminsboxActionPerformed

    private void jLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginbtnActionPerformed
        // TODO add your handling code here:
        String password = jUsernametxt.getText();
        String username = jPasswordtxt.getText();

        if (password.contains("abc") && (username.contains("sys")))
        {
            SystemAdminjFrame sa = new SystemAdminjFrame();
            //splitPane.setRightComponent(sa);
            sa.setVisible(true);
            //dispose();
        
        }
        else if (password.contains("123") && (username.contains("comm")))
        {
            CommunityAdminjFrame ca = new CommunityAdminjFrame();
            //splitPane.setRightComponent(sa);
            ca.setVisible(true);
            //dispose();
        }
        else if (password.contains("xyz") && (username.contains("hospital")))
        {
            HospitalAdminjFrame ha = new HospitalAdminjFrame();
            //splitPane.setRightComponent(sa);
            ha.setVisible(true);
           // dispose();
        }
        /*else if (password.contains("456") && (username.contains("doctor")))
        {
            DoctorJPanel df = new DoctorjPanel();
            //splitPane.setRightComponent(df);
            df.setVisible(true);
            dispose();
        }
        */
        else
        {
            JOptionPane.showMessageDialog(this ,"Please enter correct Username and Password");
            jUsernametxt.setText(null);
            jPasswordtxt.setText(null);
        }
    }//GEN-LAST:event_jLoginbtnActionPerformed

    private void jBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackbtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jBackbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdminHeading;
    private javax.swing.JComboBox<String> jAdminsbox;
    private javax.swing.JButton jBackbtn;
    private javax.swing.JButton jCancelbtn;
    private javax.swing.JButton jLoginbtn;
    private javax.swing.JLabel jPasswordlbl;
    private javax.swing.JTextField jPasswordtxt;
    private javax.swing.JLabel jSelectadminlbl;
    private javax.swing.JLabel jUsernamelbl;
    private javax.swing.JTextField jUsernametxt;
    // End of variables declaration//GEN-END:variables
}
