/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author srikr
 */
public class HospitalAdminjFrame extends javax.swing.JFrame {

    /**
     * Creates new form HospitalAdminjFrame
     */
    public HospitalAdminjFrame() {
        initComponents();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackbtn2 = new javax.swing.JButton();
        jHomebtn = new javax.swing.JButton();
        jSystemadminheadinglbl = new javax.swing.JLabel();
        jSplitPane = new javax.swing.JSplitPane();
        jMenupnl = new javax.swing.JPanel();
        jPatientbtn = new javax.swing.JButton();
        jDoctorbtn = new javax.swing.JButton();
        jHospitalbtn = new javax.swing.JButton();
        jEncounterbtn = new javax.swing.JButton();
        jDisplaypnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBackbtn2.setText("BACK");
        jBackbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackbtn2ActionPerformed(evt);
            }
        });

        jHomebtn.setText("HOME");
        jHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomebtnActionPerformed(evt);
            }
        });

        jSystemadminheadinglbl.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jSystemadminheadinglbl.setText("HOSPITAL ADMIN");

        jPatientbtn.setText("PATIENT");
        jPatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientbtnActionPerformed(evt);
            }
        });

        jDoctorbtn.setText("DOCTOR");
        jDoctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorbtnActionPerformed(evt);
            }
        });

        jHospitalbtn.setText("HOSPITAL");
        jHospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHospitalbtnActionPerformed(evt);
            }
        });

        jEncounterbtn.setText("ENCOUNTER");
        jEncounterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEncounterbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMenupnlLayout = new javax.swing.GroupLayout(jMenupnl);
        jMenupnl.setLayout(jMenupnlLayout);
        jMenupnlLayout.setHorizontalGroup(
            jMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenupnlLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEncounterbtn)
                    .addComponent(jHospitalbtn)
                    .addComponent(jDoctorbtn)
                    .addComponent(jPatientbtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenupnlLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDoctorbtn, jEncounterbtn, jHospitalbtn, jPatientbtn});

        jMenupnlLayout.setVerticalGroup(
            jMenupnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenupnlLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPatientbtn)
                .addGap(30, 30, 30)
                .addComponent(jDoctorbtn)
                .addGap(30, 30, 30)
                .addComponent(jHospitalbtn)
                .addGap(30, 30, 30)
                .addComponent(jEncounterbtn)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jMenupnlLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDoctorbtn, jEncounterbtn, jHospitalbtn, jPatientbtn});

        jSplitPane.setLeftComponent(jMenupnl);

        javax.swing.GroupLayout jDisplaypnlLayout = new javax.swing.GroupLayout(jDisplaypnl);
        jDisplaypnl.setLayout(jDisplaypnlLayout);
        jDisplaypnlLayout.setHorizontalGroup(
            jDisplaypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDisplaypnlLayout.setVerticalGroup(
            jDisplaypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(jDisplaypnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420)
                        .addComponent(jSystemadminheadinglbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(jBackbtn2))
                    .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBackbtn2, jHomebtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackbtn2)
                    .addComponent(jSystemadminheadinglbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBackbtn2, jHomebtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackbtn2ActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jBackbtn2ActionPerformed

    private void jHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomebtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jHomebtnActionPerformed

    private void jPatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientbtnActionPerformed
        // TODO add your handling code here:
        HospitalAdminPatientjPanel hap = new HospitalAdminPatientjPanel();
        jSplitPane.setRightComponent(hap);
    }//GEN-LAST:event_jPatientbtnActionPerformed

    private void jDoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorbtnActionPerformed
        // TODO add your handling code here:
        HospitalAdminDoctorjPanel had = new HospitalAdminDoctorjPanel();
        jSplitPane.setRightComponent(had);
    }//GEN-LAST:event_jDoctorbtnActionPerformed

    private void jHospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHospitalbtnActionPerformed
        // TODO add your handling code here:
        HospitalAdminHospitaljPanel hah = new HospitalAdminHospitaljPanel();
        jSplitPane.setRightComponent(hah);
    }//GEN-LAST:event_jHospitalbtnActionPerformed

    private void jEncounterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEncounterbtnActionPerformed
        // TODO add your handling code here:
        HospitalAdminEncounterjPanel hae = new HospitalAdminEncounterjPanel();
        jSplitPane.setRightComponent(hae);
    }//GEN-LAST:event_jEncounterbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalAdminjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalAdminjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackbtn2;
    private javax.swing.JPanel jDisplaypnl;
    private javax.swing.JButton jDoctorbtn;
    private javax.swing.JButton jEncounterbtn;
    private javax.swing.JButton jHomebtn;
    private javax.swing.JButton jHospitalbtn;
    private javax.swing.JPanel jMenupnl;
    private javax.swing.JButton jPatientbtn;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel jSystemadminheadinglbl;
    // End of variables declaration//GEN-END:variables
}
