/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Source.City;
import Source.CityDirectory;
import Source.Hospital;
import Source.HospitalDirectory;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author srikr
 */
public class HospitalAdminHospitaljPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminHospitaljPanel
     */
    CityDirectory phistory;
    DefaultTableModel tableModel;
    static ArrayList<City> cityList = new ArrayList<City>();
    private HospitalDirectory hosd;
    public HospitalAdminHospitaljPanel() {
        initComponents();
        //this.hosd=hosd;
        this.phistory= new CityDirectory();
        jUpdatebtn.setEnabled(false);
        tableModel = (DefaultTableModel)jHospitaltbl.getModel();
        populateTable();
    }
    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) jHospitaltbl.getModel();
        model.setRowCount(0);
        
        for (City pd : phistory.getCity()){
          
            Object[] row = new Object[3];
            row[0] = pd.getCityName();
            row[1] = pd.getCommunity();
            row[2] = pd.getHospital();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCommunitylbl = new javax.swing.JLabel();
        jReadbtn = new javax.swing.JButton();
        jHospitallbl = new javax.swing.JLabel();
        jHospitaldetailslbl = new javax.swing.JLabel();
        jHospitaltxt = new javax.swing.JTextField();
        jHScrollPane = new javax.swing.JScrollPane();
        jHospitaltbl = new javax.swing.JTable();
        jSearchtxt = new javax.swing.JTextField();
        jSearchbtn = new javax.swing.JButton();
        jCreatebtn = new javax.swing.JButton();
        jUpdatebtn = new javax.swing.JButton();
        jCitylbl = new javax.swing.JLabel();
        jCitytxt = new javax.swing.JTextField();
        jCommunitytxt = new javax.swing.JTextField();

        jCommunitylbl.setText("Community");

        jReadbtn.setBackground(new java.awt.Color(255, 204, 51));
        jReadbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jReadbtn.setText("READ");
        jReadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadbtnActionPerformed(evt);
            }
        });

        jHospitallbl.setText("Hospital");

        jHospitaldetailslbl.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jHospitaldetailslbl.setText("HOSPITAL DETAILS :");

        jHospitaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHospitaltxtActionPerformed(evt);
            }
        });
        jHospitaltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jHospitaltxtKeyTyped(evt);
            }
        });

        jHospitaltbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Community", "City"
            }
        ));
        jHScrollPane.setViewportView(jHospitaltbl);

        jSearchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchtxtActionPerformed(evt);
            }
        });

        jSearchbtn.setBackground(new java.awt.Color(255, 204, 51));
        jSearchbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jSearchbtn.setText("SEARCH");
        jSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchbtnActionPerformed(evt);
            }
        });

        jCreatebtn.setBackground(new java.awt.Color(255, 204, 51));
        jCreatebtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCreatebtn.setText("CREATE");
        jCreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreatebtnActionPerformed(evt);
            }
        });

        jUpdatebtn.setBackground(new java.awt.Color(255, 204, 51));
        jUpdatebtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jUpdatebtn.setText("UPDATE");
        jUpdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdatebtnActionPerformed(evt);
            }
        });

        jCitylbl.setText("City");

        jCitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCitytxtActionPerformed(evt);
            }
        });
        jCitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCitytxtKeyTyped(evt);
            }
        });

        jCommunitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunitytxtActionPerformed(evt);
            }
        });
        jCommunitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCommunitytxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHospitaldetailslbl)
                        .addGap(18, 18, 18)
                        .addComponent(jSearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSearchbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                        .addGap(356, 356, 356))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCreatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jUpdatebtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jReadbtn)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCommunitylbl)
                                            .addComponent(jCitylbl)
                                            .addComponent(jHospitallbl))
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHospitaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jCitytxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCommunitytxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCreatebtn, jReadbtn, jSearchbtn, jUpdatebtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSearchbtn)
                        .addComponent(jSearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jHospitaldetailslbl))
                .addGap(18, 18, 18)
                .addComponent(jHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jReadbtn)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCitylbl)
                    .addComponent(jCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCommunitylbl)
                    .addComponent(jCommunitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHospitallbl)
                    .addComponent(jHospitaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdatebtn))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCreatebtn, jReadbtn, jSearchbtn, jUpdatebtn});

    }// </editor-fold>//GEN-END:initComponents

    private void jReadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadbtnActionPerformed
        // TODO add your handling code here:
        jUpdatebtn.setEnabled(true);
        int selectedrow = jHospitaltbl.getSelectedRow();
        if (selectedrow < 0){
            JOptionPane.showMessageDialog(null, "please select");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jHospitaltbl.getModel();
        String hospital = model.getValueAt(jHospitaltbl.getSelectedRow(),0).toString();
        String community = model.getValueAt(jHospitaltbl.getSelectedRow(),1).toString();
        String city = model.getValueAt(jHospitaltbl.getSelectedRow(),2).toString();

        jHospitaltxt.setText(hospital);
        jCommunitytxt.setText(community);
        jCitytxt.setText(city);
    }//GEN-LAST:event_jReadbtnActionPerformed

    private void jHospitaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHospitaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHospitaltxtActionPerformed

    private void jHospitaltxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHospitaltxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jHospitaltxtKeyTyped

    private void jSearchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchtxtActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jHospitaltbl.getModel();
        TableRowSorter<DefaultTableModel> tm = new TableRowSorter<>(model);
        jHospitaltbl.setRowSorter(tm);
        tm.setRowFilter(RowFilter.regexFilter(jSearchtxt.getText().trim()));
    }//GEN-LAST:event_jSearchtxtActionPerformed

    private void jSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jHospitaltbl.getModel();
        TableRowSorter<DefaultTableModel> tm = new TableRowSorter<>(model);
        jHospitaltbl.setRowSorter(tm);
        tm.setRowFilter(RowFilter.regexFilter(jSearchtxt.getText().trim()));
    }//GEN-LAST:event_jSearchbtnActionPerformed

    private void jCreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreatebtnActionPerformed
        // TODO add your handling code here:
        String cityName = jCitytxt.getText();
        String community = jCommunitytxt.getText();
        String hospital=jHospitaltxt.getText();
        if(cityName.isEmpty() || community.isEmpty() || hospital.isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Enter all Fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            City city=new City(cityName,community,hospital);
            cityList.add(city);
            Object[] data = {cityName, community,hospital};
            tableModel.addRow(data);
            City c = phistory.addNewCityDetails();
            c.setCityName(cityName);
            c.setCommunity(community);
            c.setHospital(hospital);
            populateTable();
            JOptionPane.showMessageDialog(this,
                "City Data Saved",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        }
        jCitytxt.setText("");
        jCommunitytxt.setText("");
        jHospitaltxt.setText("");
    }//GEN-LAST:event_jCreatebtnActionPerformed

    private void jUpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdatebtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jHospitaltbl.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jHospitaltbl.getModel();
        if (selectedRowIndex >= 0)
        {
            if("".equals(jHospitaltxt.getText())||"".equals(jCommunitytxt.getText())||
                "".equals(jCitytxt.getText()))             {

                JOptionPane.showMessageDialog(this, "Please Fill All the Fields");
            }
            else{
                model.setValueAt(jHospitaltxt.getText(), selectedRowIndex, 0);
                model.setValueAt(jCommunitytxt.getText(), selectedRowIndex, 1);
                model.setValueAt(jCitytxt.getText(), selectedRowIndex, 2);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please Select a row to View.");
        }
        jHospitaltxt.setText("");
        jCommunitytxt.setText("");
        jCitytxt.setText("");
    }//GEN-LAST:event_jUpdatebtnActionPerformed

    private void jCitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCitytxtActionPerformed

    private void jCitytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCitytxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jCitytxtKeyTyped

    private void jCommunitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCommunitytxtActionPerformed

    private void jCommunitytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommunitytxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jCommunitytxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JTextField jCitytxt;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JTextField jCommunitytxt;
    private javax.swing.JButton jCreatebtn;
    private javax.swing.JScrollPane jHScrollPane;
    private javax.swing.JLabel jHospitaldetailslbl;
    private javax.swing.JLabel jHospitallbl;
    private javax.swing.JTable jHospitaltbl;
    private javax.swing.JTextField jHospitaltxt;
    private javax.swing.JButton jReadbtn;
    private javax.swing.JButton jSearchbtn;
    private javax.swing.JTextField jSearchtxt;
    private javax.swing.JButton jUpdatebtn;
    // End of variables declaration//GEN-END:variables
}
