/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Source.PersonDirectory;
import Source.PatientDirectory;

/**
 *
 * @author srikr
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    int personid = 22000;
    PersonDirectory person;
    PatientDirectory patient;
    public MainFrame() {
        initComponents();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        person = new PersonDirectory();
        patient = new PatientDirectory();
        personid = personid+1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jMenuPanel = new javax.swing.JPanel();
        jHomebtn = new javax.swing.JButton();
        jPatientbtn = new javax.swing.JButton();
        jDoctorbtn = new javax.swing.JButton();
        jAdminbtn = new javax.swing.JButton();
        jRefreshbtn = new javax.swing.JButton();
        jExitbtn = new javax.swing.JButton();
        jPersonbtn = new javax.swing.JButton();
        jHomePanel = new javax.swing.JPanel();
        jHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jStatement = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME");

        jMenuPanel.setBackground(new java.awt.Color(0, 0, 0));

        jHomebtn.setBackground(new java.awt.Color(255, 204, 51));
        jHomebtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jHomebtn.setText("HOME");
        jHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomebtnActionPerformed(evt);
            }
        });

        jPatientbtn.setBackground(new java.awt.Color(255, 204, 51));
        jPatientbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPatientbtn.setText("PATIENT");
        jPatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientbtnActionPerformed(evt);
            }
        });

        jDoctorbtn.setBackground(new java.awt.Color(255, 204, 51));
        jDoctorbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jDoctorbtn.setText("DOCTOR");
        jDoctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoctorbtnActionPerformed(evt);
            }
        });

        jAdminbtn.setBackground(new java.awt.Color(255, 204, 51));
        jAdminbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAdminbtn.setText("ADMIN");
        jAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminbtnActionPerformed(evt);
            }
        });

        jRefreshbtn.setBackground(new java.awt.Color(255, 204, 51));
        jRefreshbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jRefreshbtn.setText("REFRESH");
        jRefreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshbtnActionPerformed(evt);
            }
        });

        jExitbtn.setBackground(new java.awt.Color(255, 204, 51));
        jExitbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jExitbtn.setText("EXIT");
        jExitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitbtnActionPerformed(evt);
            }
        });

        jPersonbtn.setBackground(new java.awt.Color(255, 204, 51));
        jPersonbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPersonbtn.setText("PERSON");
        jPersonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersonbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMenuPanelLayout = new javax.swing.GroupLayout(jMenuPanel);
        jMenuPanel.setLayout(jMenuPanelLayout);
        jMenuPanelLayout.setHorizontalGroup(
            jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelLayout.createSequentialGroup()
                .addGroup(jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDoctorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRefreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPersonbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAdminbtn, jDoctorbtn, jExitbtn, jPatientbtn, jRefreshbtn});

        jMenuPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jHomebtn, jPersonbtn});

        jMenuPanelLayout.setVerticalGroup(
            jMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuPanelLayout.createSequentialGroup()
                .addComponent(jHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(jPersonbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPatientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jDoctorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jAdminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jRefreshbtn)
                .addGap(12, 12, 12)
                .addComponent(jExitbtn))
        );

        jMenuPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAdminbtn, jDoctorbtn, jExitbtn, jHomebtn, jPatientbtn, jPersonbtn, jRefreshbtn});

        jSplitPane.setLeftComponent(jMenuPanel);

        jHomePanel.setBackground(new java.awt.Color(0, 0, 0));

        jHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 38)); // NOI18N
        jHeading.setForeground(new java.awt.Color(255, 255, 255));
        jHeading.setText("HOSPITAL MANAGEMENT SYSTEM");

        jStatement.setBackground(new java.awt.Color(0, 0, 0));
        jStatement.setColumns(20);
        jStatement.setFont(new java.awt.Font("Segoe UI Variable", 2, 24)); // NOI18N
        jStatement.setForeground(new java.awt.Color(255, 255, 255));
        jStatement.setRows(5);
        jStatement.setText("“Our mission is to bring healthcare of International standards within the reach of every individual. \nWe are committed to the achievement and maintenance of excellence in education, research and \nhealthcare for the benefit of humanity”");
        jScrollPane1.setViewportView(jStatement);

        javax.swing.GroupLayout jHomePanelLayout = new javax.swing.GroupLayout(jHomePanel);
        jHomePanel.setLayout(jHomePanelLayout);
        jHomePanelLayout.setHorizontalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(317, 317, 317))
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jHomePanelLayout.setVerticalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addComponent(jHeading)
                .addGap(186, 186, 186)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 243, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jHomePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomebtnActionPerformed
        // TODO add your handling code here:
        jSplitPane.setRightComponent(jHomePanel);
    }//GEN-LAST:event_jHomebtnActionPerformed

    private void jPatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientbtnActionPerformed
        // TODO add your handling code here:
        PatientLoginjFrame patientlogin = new PatientLoginjFrame();
        patientlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPatientbtnActionPerformed

    private void jDoctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoctorbtnActionPerformed
        // TODO add your handling code here:
        DoctorLoginjFrame doctorframe = new DoctorLoginjFrame();
        doctorframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDoctorbtnActionPerformed

    private void jAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminbtnActionPerformed
        // TODO add your handling code here:
        AdminjFrame admin = new AdminjFrame();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAdminbtnActionPerformed

    private void jRefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshbtnActionPerformed
        // TODO add your handling code here:
        MainFrame mainframe = new MainFrame();
        mainframe.show();
        dispose();
    }//GEN-LAST:event_jRefreshbtnActionPerformed

    private void jExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jExitbtnActionPerformed

    private void jPersonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersonbtnActionPerformed
        // TODO add your handling code here:
        PersonjPanel personpanel = new PersonjPanel(person, patient);
        jSplitPane.setRightComponent(personpanel);
        
    }//GEN-LAST:event_jPersonbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdminbtn;
    private javax.swing.JButton jDoctorbtn;
    private javax.swing.JButton jExitbtn;
    private javax.swing.JLabel jHeading;
    private javax.swing.JPanel jHomePanel;
    private javax.swing.JButton jHomebtn;
    private javax.swing.JPanel jMenuPanel;
    private javax.swing.JButton jPatientbtn;
    private javax.swing.JButton jPersonbtn;
    private javax.swing.JButton jRefreshbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTextArea jStatement;
    // End of variables declaration//GEN-END:variables
}
