/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Source.City;
import Source.Patient;
import Source.PatientDirectory;
import Source.Person;
import Source.PersonDirectory;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srikr
 */
public class PatientDetailsjFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientDetailsjFrame
     */
    PersonDirectory person;
    PatientDirectory patient;
    public PatientDetailsjFrame() {
        initComponents();
        loadComboBoxData();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        //jNametxt.setEditable(false);
        //jAgetxt.setEditable(false);
        //jPhonenotxt.setEditable(false);
        //jEmailidtxt.setEditable(false);
        //jAddresstxt.setEditable(false);
        //jCommunitytxt.setEditable(false);
        //jCitytxt.setEditable(false);
        this.person = new PersonDirectory();
        this.patient = new PatientDirectory();
        loadComboBoxData();

    }
    public PatientDetailsjFrame(PersonDirectory pd) {
        initComponents();
        loadComboBoxData();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenderbtngrp = new javax.swing.ButtonGroup();
        jPhonenotxt = new javax.swing.JTextField();
        jAgelbl = new javax.swing.JLabel();
        jPEncounterPane = new javax.swing.JScrollPane();
        jPEncountertbl = new javax.swing.JTable();
        jEmailidtxt = new javax.swing.JTextField();
        jCommunitylbl = new javax.swing.JLabel();
        jEncountersHeading = new javax.swing.JLabel();
        jAddresstxt = new javax.swing.JTextField();
        jBackbtn = new javax.swing.JButton();
        jCitylbl = new javax.swing.JLabel();
        jDCReadbtn = new javax.swing.JButton();
        jPEReadbtn = new javax.swing.JButton();
        jAddresslbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPhonenolbl = new javax.swing.JLabel();
        jPIEditbtn = new javax.swing.JButton();
        jPISavebtn = new javax.swing.JButton();
        jMalebtn = new javax.swing.JRadioButton();
        jFemalebtn = new javax.swing.JRadioButton();
        jPersonidlbl = new javax.swing.JLabel();
        jLgbtqbtn = new javax.swing.JRadioButton();
        jPersonidtxt = new javax.swing.JTextField();
        jEmailidlbl = new javax.swing.JLabel();
        jNametxt = new javax.swing.JTextField();
        jGenderlbl = new javax.swing.JLabel();
        jPatientHeading = new javax.swing.JLabel();
        jAgetxt = new javax.swing.JTextField();
        jDoctorComPane = new javax.swing.JScrollPane();
        jDoctorComtbl = new javax.swing.JTable();
        jNamelbl = new javax.swing.JLabel();
        jDoctorcomHeading = new javax.swing.JLabel();
        jLogoutbtn = new javax.swing.JButton();
        jSearchbtn = new javax.swing.JButton();
        jCitycmb = new javax.swing.JComboBox<>();
        jCommunitycmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPhonenotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPhonenotxtKeyTyped(evt);
            }
        });

        jAgelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAgelbl.setText("Age :");

        jPEncountertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPEncounterPane.setViewportView(jPEncountertbl);

        jCommunitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCommunitylbl.setText("Community :");

        jEncountersHeading.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jEncountersHeading.setText("Personal Encounters");

        jBackbtn.setText("HOME");
        jBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackbtnActionPerformed(evt);
            }
        });

        jCitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCitylbl.setText("City :");

        jDCReadbtn.setText("READ");
        jDCReadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDCReadbtnActionPerformed(evt);
            }
        });

        jPEReadbtn.setText("READ");

        jAddresslbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAddresslbl.setText("Address :");

        jButton1.setText("BOOK APPOINTMENT");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Personal Information");

        jPhonenolbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPhonenolbl.setText("Phone Number :");

        jPIEditbtn.setText("EDIT");

        jPISavebtn.setText("SAVE");

        jGenderbtngrp.add(jMalebtn);
        jMalebtn.setText("Male");

        jGenderbtngrp.add(jFemalebtn);
        jFemalebtn.setText("Female");

        jPersonidlbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jPersonidlbl.setText("Please Enter Person Unique ID :");

        jGenderbtngrp.add(jLgbtqbtn);
        jLgbtqbtn.setText("LGBTQ+");

        jPersonidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersonidtxtActionPerformed(evt);
            }
        });

        jEmailidlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jEmailidlbl.setText("Email ID :");

        jNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNametxtKeyTyped(evt);
            }
        });

        jGenderlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jGenderlbl.setText("Gender :");

        jPatientHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jPatientHeading.setText("PATIENT");

        jAgetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgetxtActionPerformed(evt);
            }
        });
        jAgetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAgetxtKeyTyped(evt);
            }
        });

        jDoctorComtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jDoctorComPane.setViewportView(jDoctorComtbl);

        jNamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jNamelbl.setText("Name :");

        jDoctorcomHeading.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jDoctorcomHeading.setText("Doctors in the Community");

        jLogoutbtn.setText("LOGOUT");
        jLogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutbtnActionPerformed(evt);
            }
        });

        jSearchbtn.setText("Search");
        jSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jBackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPatientHeading)
                .addGap(401, 401, 401)
                .addComponent(jLogoutbtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPersonidlbl)
                        .addGap(18, 18, 18)
                        .addComponent(jPersonidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSearchbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNamelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAgelbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jAgetxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGenderlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPhonenolbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMalebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFemalebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLgbtqbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCommunitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAddresslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAddresstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jCommunitycmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDCReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jDoctorcomHeading)
                            .addComponent(jDoctorComPane, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPEReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEncountersHeading)
                            .addComponent(jPEncounterPane, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPIEditbtn)
                                .addGap(18, 18, 18)
                                .addComponent(jPISavebtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jEmailidlbl)
                                .addGap(6, 6, 6)
                                .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBackbtn, jLogoutbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPatientHeading)
                    .addComponent(jBackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogoutbtn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPersonidlbl)
                    .addComponent(jPersonidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchbtn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddresslbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCommunitylbl)
                            .addComponent(jCommunitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMalebtn)
                            .addComponent(jFemalebtn)
                            .addComponent(jLgbtqbtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhonenolbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jNamelbl)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAgelbl)))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailidlbl)
                    .addComponent(jCitylbl)
                    .addComponent(jCitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPIEditbtn)
                    .addComponent(jPISavebtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDoctorcomHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDoctorComPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEncountersHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPEncounterPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDCReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jPEReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBackbtn, jLogoutbtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackbtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jBackbtnActionPerformed

    private void jDCReadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDCReadbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCReadbtnActionPerformed

    private void jPersonidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersonidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPersonidtxtActionPerformed

    private void jAgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgetxtActionPerformed

    private void jLogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutbtnActionPerformed
        // TODO add your handling code here:
        PatientLoginjFrame patientlogin = new PatientLoginjFrame();
        patientlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutbtnActionPerformed

    private void jSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchbtnActionPerformed
        // TODO add your handling code here:
        String patient =jPersonidtxt.getText();
        Person p = new Person();
        for(Person per : person.getPerson()){
            if (String.valueOf(per.getPersonid()).equals(patient))
            {
                jNametxt.setText(p.getName());
                jAgetxt.setText(String.valueOf(p.getAge()));
                if (p.getGender().equals("Male"))
                {
                    //genderGroup.setSelected((ButtonModel) btnMale, true);
                    jMalebtn.setSelected(true);
                }
                else if (p.getGender().equals("Female"))
                {
                    //genderGroup.setSelected(btnF, true);
                    jFemalebtn.setSelected(true);
                }
                else
                {
                    jLgbtqbtn.setSelected(true);
                }
                jPhonenotxt.setText(String.valueOf(p.getPhoneno()));
                jEmailidtxt.setText(p.getEmailid());
                jAddresstxt.setText(p.getAddress());
                jCitycmb.setSelectedItem(p.getCity());  
                jCommunitycmb.setSelectedItem(p.getCommunity());
                break;
            }
        } 
    }//GEN-LAST:event_jSearchbtnActionPerformed

    private void jNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNametxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jNametxtKeyTyped

    private void jAgetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jAgetxtKeyTyped

    private void jPhonenotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhonenotxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jPhonenotxtKeyTyped

    private void loadComboBoxData(){
        jCitycmb.removeAllItems();
        jCommunitycmb.removeAllItems();
        for(City city: SystemHospitaljPanel.cityList){
            jCitycmb.addItem(city.getCityName());
        }
        for(City city:SystemHospitaljPanel.cityList){
            jCommunitycmb.addItem(city.getCommunity());
        }
        jCitycmb.setSelectedIndex(-1);
        jCommunitycmb.setSelectedIndex(-1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDetailsjFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddresslbl;
    private javax.swing.JTextField jAddresstxt;
    private javax.swing.JLabel jAgelbl;
    private javax.swing.JTextField jAgetxt;
    private javax.swing.JButton jBackbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCitycmb;
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JComboBox<String> jCommunitycmb;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JButton jDCReadbtn;
    private javax.swing.JScrollPane jDoctorComPane;
    private javax.swing.JTable jDoctorComtbl;
    private javax.swing.JLabel jDoctorcomHeading;
    private javax.swing.JLabel jEmailidlbl;
    private javax.swing.JTextField jEmailidtxt;
    private javax.swing.JLabel jEncountersHeading;
    private javax.swing.JRadioButton jFemalebtn;
    private javax.swing.ButtonGroup jGenderbtngrp;
    private javax.swing.JLabel jGenderlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jLgbtqbtn;
    private javax.swing.JButton jLogoutbtn;
    private javax.swing.JRadioButton jMalebtn;
    private javax.swing.JLabel jNamelbl;
    private javax.swing.JTextField jNametxt;
    private javax.swing.JButton jPEReadbtn;
    private javax.swing.JScrollPane jPEncounterPane;
    private javax.swing.JTable jPEncountertbl;
    private javax.swing.JButton jPIEditbtn;
    private javax.swing.JButton jPISavebtn;
    private javax.swing.JLabel jPatientHeading;
    private javax.swing.JLabel jPersonidlbl;
    private javax.swing.JTextField jPersonidtxt;
    private javax.swing.JLabel jPhonenolbl;
    private javax.swing.JTextField jPhonenotxt;
    private javax.swing.JButton jSearchbtn;
    // End of variables declaration//GEN-END:variables
}
