/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Source.City;
import Source.Doctor;
import Source.DoctorDirectory;
import Source.Encounter;
import Source.EncounterHistory;
import Source.Patient;
import Source.PatientDirectory;
import Source.Person;
import Source.PersonDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author srikr
 */
public class PatientDetailsjFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientDetailsjFrame
     */
    int g=0;
    private PersonDirectory person;
    private PatientDirectory patient;
    private DoctorDirectory perform;
    private EncounterHistory ehistory;
    public PatientDetailsjFrame() {
        initComponents();
        loadComboBoxData();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        this.person = new PersonDirectory();
        this.patient = new PatientDirectory();
        this.ehistory=new EncounterHistory();
        loadComboBoxData();
        populateDocTable();
        populateEncTable();

    }
    public PatientDetailsjFrame(PersonDirectory pd) {
        initComponents();
        loadComboBoxData();
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        this.person = new PersonDirectory();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenderbtngrp = new javax.swing.ButtonGroup();
        jPhonenotxt = new javax.swing.JTextField();
        jAgelbl = new javax.swing.JLabel();
        jPEncounterPane = new javax.swing.JScrollPane();
        jPEncountertbl = new javax.swing.JTable();
        jEmailidtxt = new javax.swing.JTextField();
        jCommunitylbl = new javax.swing.JLabel();
        jEncountersHeading = new javax.swing.JLabel();
        jAddresstxt = new javax.swing.JTextField();
        jBackbtn = new javax.swing.JButton();
        jCitylbl = new javax.swing.JLabel();
        jDCReadbtn = new javax.swing.JButton();
        jAddresslbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPhonenolbl = new javax.swing.JLabel();
        jPIEditbtn = new javax.swing.JButton();
        jPISavebtn = new javax.swing.JButton();
        jMalebtn = new javax.swing.JRadioButton();
        jFemalebtn = new javax.swing.JRadioButton();
        jPersonidlbl = new javax.swing.JLabel();
        jLgbtqbtn = new javax.swing.JRadioButton();
        jPersonidtxt = new javax.swing.JTextField();
        jEmailidlbl = new javax.swing.JLabel();
        jNametxt = new javax.swing.JTextField();
        jGenderlbl = new javax.swing.JLabel();
        jPatientHeading = new javax.swing.JLabel();
        jAgetxt = new javax.swing.JTextField();
        jDoctorComPane = new javax.swing.JScrollPane();
        jDoctorComtbl = new javax.swing.JTable();
        jNamelbl = new javax.swing.JLabel();
        jDoctorcomHeading = new javax.swing.JLabel();
        jLogoutbtn = new javax.swing.JButton();
        jSearchbtn = new javax.swing.JButton();
        jCitycmb = new javax.swing.JComboBox<>();
        jCommunitycmb = new javax.swing.JComboBox<>();
        jDoctorlbl = new javax.swing.JLabel();
        jHospitallbl = new javax.swing.JLabel();
        jDoctortxt = new javax.swing.JTextField();
        jHospitaltxt = new javax.swing.JTextField();
        jRRatelbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jHRatelbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAbnormallbl = new javax.swing.JLabel();
        jAbnormaltxt = new javax.swing.JComboBox<>();
        jRRatetxt = new javax.swing.JTextField();
        jPatienttxt = new javax.swing.JTextField();
        jHRatetxt = new javax.swing.JTextField();
        jDoctortxt1 = new javax.swing.JTextField();
        jHeightlbl = new javax.swing.JLabel();
        jReadbtn = new javax.swing.JButton();
        jHeighttxt = new javax.swing.JTextField();
        jWeighttxt = new javax.swing.JTextField();
        jWeightlbl = new javax.swing.JLabel();
        jPatientlbl = new javax.swing.JLabel();
        jDoctorlbl1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jEncountertxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PATIENT");

        jPhonenotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPhonenotxtKeyTyped(evt);
            }
        });

        jAgelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAgelbl.setText("Age :");

        jPEncountertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Doctor Name", "Encounter ID", "Respiration Rate", "Heart Rate", "Height", "Weight", "Abnormal"
            }
        ));
        jPEncounterPane.setViewportView(jPEncountertbl);

        jCommunitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCommunitylbl.setText("Community :");

        jEncountersHeading.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jEncountersHeading.setText("Personal Encounters");

        jBackbtn.setBackground(new java.awt.Color(255, 204, 51));
        jBackbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jBackbtn.setText("HOME");
        jBackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackbtnActionPerformed(evt);
            }
        });

        jCitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCitylbl.setText("City :");

        jDCReadbtn.setBackground(new java.awt.Color(255, 204, 51));
        jDCReadbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jDCReadbtn.setText("READ");
        jDCReadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDCReadbtnActionPerformed(evt);
            }
        });

        jAddresslbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAddresslbl.setText("Address :");

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("BOOK APPOINTMENT");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Personal Information");

        jPhonenolbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPhonenolbl.setText("Phone Number :");

        jPIEditbtn.setBackground(new java.awt.Color(255, 204, 51));
        jPIEditbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPIEditbtn.setText("EDIT");
        jPIEditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPIEditbtnActionPerformed(evt);
            }
        });

        jPISavebtn.setBackground(new java.awt.Color(255, 204, 51));
        jPISavebtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPISavebtn.setText("SAVE");
        jPISavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPISavebtnActionPerformed(evt);
            }
        });

        jGenderbtngrp.add(jMalebtn);
        jMalebtn.setText("Male");

        jGenderbtngrp.add(jFemalebtn);
        jFemalebtn.setText("Female");

        jPersonidlbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jPersonidlbl.setText("Please Enter Person Unique ID :");

        jGenderbtngrp.add(jLgbtqbtn);
        jLgbtqbtn.setText("LGBTQ+");

        jPersonidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersonidtxtActionPerformed(evt);
            }
        });

        jEmailidlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jEmailidlbl.setText("Email ID :");

        jNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNametxtKeyTyped(evt);
            }
        });

        jGenderlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jGenderlbl.setText("Gender :");

        jPatientHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jPatientHeading.setText("PATIENT");

        jAgetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgetxtActionPerformed(evt);
            }
        });
        jAgetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAgetxtKeyTyped(evt);
            }
        });

        jDoctorComtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Hospital"
            }
        ));
        jDoctorComPane.setViewportView(jDoctorComtbl);

        jNamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jNamelbl.setText("Name :");

        jDoctorcomHeading.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jDoctorcomHeading.setText("Doctors in the Community");

        jLogoutbtn.setBackground(new java.awt.Color(255, 204, 51));
        jLogoutbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLogoutbtn.setText("LOGOUT");
        jLogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutbtnActionPerformed(evt);
            }
        });

        jSearchbtn.setText("Search");
        jSearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchbtnActionPerformed(evt);
            }
        });

        jDoctorlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jDoctorlbl.setText("Doctor Name :");

        jHospitallbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jHospitallbl.setText("Hospital Name :");

        jRRatelbl.setText("Respiration Rate :");

        jLabel2.setText("Cms");

        jHRatelbl.setText("Heart Rate :");

        jLabel3.setText("Kgs");

        jAbnormallbl.setText("Abnormal :");

        jAbnormaltxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "false", "true" }));

        jRRatetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jRRatetxtKeyTyped(evt);
            }
        });

        jPatienttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPatienttxtKeyTyped(evt);
            }
        });

        jHRatetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jHRatetxtKeyTyped(evt);
            }
        });

        jDoctortxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDoctortxt1KeyTyped(evt);
            }
        });

        jHeightlbl.setText("Height :");

        jReadbtn.setBackground(new java.awt.Color(255, 204, 51));
        jReadbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jReadbtn.setText("READ");
        jReadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadbtnActionPerformed(evt);
            }
        });

        jHeighttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jHeighttxtKeyTyped(evt);
            }
        });

        jWeighttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jWeighttxtKeyTyped(evt);
            }
        });

        jWeightlbl.setText("Weight :");

        jPatientlbl.setText("Patient Name :");

        jDoctorlbl1.setText("Doctor Name :");

        jLabel4.setText("Encounter ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jBackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPatientHeading)
                .addGap(401, 401, 401)
                .addComponent(jLogoutbtn))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEncountersHeading)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPIEditbtn)
                        .addGap(18, 18, 18)
                        .addComponent(jPISavebtn))
                    .addComponent(jPEncounterPane, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jPersonidlbl)
                                .addGap(18, 18, 18)
                                .addComponent(jPersonidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSearchbtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNamelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAgelbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jAgetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGenderlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPhonenolbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jMalebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFemalebtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLgbtqbtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCommunitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jAddresslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jAddresstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jCommunitycmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jEmailidlbl)
                                        .addGap(6, 6, 6)
                                        .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDCReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addComponent(jDoctorcomHeading)
                                    .addComponent(jDoctorComPane, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDoctorlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jHospitallbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDoctortxt, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(jHospitaltxt))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPatientlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRRatelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jHeightlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jRRatetxt)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jHeighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPatienttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jHRatelbl)
                                    .addComponent(jDoctorlbl1)
                                    .addComponent(jWeightlbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDoctortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAbnormallbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAbnormaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jEncountertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jWeighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(218, 218, 218)))))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBackbtn, jLogoutbtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDoctortxt, jEmailidtxt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDoctortxt1, jHRatetxt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jDCReadbtn, jPIEditbtn, jPISavebtn, jReadbtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPatientHeading)
                    .addComponent(jBackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogoutbtn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPersonidlbl)
                    .addComponent(jPersonidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearchbtn))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddresslbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCommunitylbl)
                            .addComponent(jCommunitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMalebtn)
                            .addComponent(jFemalebtn)
                            .addComponent(jLgbtqbtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPhonenolbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jNamelbl)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAgelbl)))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmailidlbl)
                    .addComponent(jCitylbl)
                    .addComponent(jCitycmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPIEditbtn)
                    .addComponent(jPISavebtn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDoctorcomHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDoctorComPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEncountersHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPEncounterPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDCReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jReadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDoctorlbl)
                            .addComponent(jDoctortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHospitallbl)
                            .addComponent(jHospitaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPatientlbl)
                            .addComponent(jDoctorlbl1)
                            .addComponent(jPatienttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDoctortxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jEncountertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRRatelbl)
                            .addComponent(jHRatelbl)
                            .addComponent(jAbnormallbl)
                            .addComponent(jRRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHRatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAbnormaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHeightlbl)
                            .addComponent(jHeighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWeightlbl)
                            .addComponent(jWeighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBackbtn, jLogoutbtn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDoctortxt, jEmailidtxt});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jDCReadbtn, jPIEditbtn, jPISavebtn, jReadbtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackbtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jBackbtnActionPerformed

    private void jDCReadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDCReadbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = jDoctorComtbl.getSelectedRow();
        if (selectedrow < 0){
            JOptionPane.showMessageDialog(null, "please select");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jDoctorComtbl.getModel();
        String doctor = model.getValueAt(jDoctorComtbl.getSelectedRow(),0).toString();
        String hospital = model.getValueAt(jDoctorComtbl.getSelectedRow(),1).toString();
        
        jDoctortxt.setText(doctor);
        jHospitaltxt.setText(hospital);
    }//GEN-LAST:event_jDCReadbtnActionPerformed

    private void jPersonidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersonidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPersonidtxtActionPerformed

    private void jAgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgetxtActionPerformed

    private void jLogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutbtnActionPerformed
        // TODO add your handling code here:
        PatientLoginjFrame patientlogin = new PatientLoginjFrame();
        patientlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutbtnActionPerformed

    private void jSearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchbtnActionPerformed
        // TODO add your handling code here:
        int s=0;
        int id= Integer.parseInt(jPersonidtxt.getText());
        for(Person p : person.getPerson()){
            int pid = p.getPersonid();
            if (id==pid)
            {
                s=1;
                jNametxt.setText(p.getName());
                jAgetxt.setText(String.valueOf(p.getAge()));
                if (p.getGender().equals("Male"))
                {
                    //genderGroup.setSelected((ButtonModel) btnMale, true);
                    jMalebtn.setSelected(true);
                }
                else if (p.getGender().equals("Female"))
                {
                    //genderGroup.setSelected(btnF, true);
                    jFemalebtn.setSelected(true);
                }
                else
                {
                    jLgbtqbtn.setSelected(true);
                }
                jPhonenotxt.setText(String.valueOf(p.getPhoneno()));
                jEmailidtxt.setText(p.getEmailid());
                jAddresstxt.setText(p.getAddress());
                jCitycmb.setSelectedItem(p.getCity());  
                jCommunitycmb.setSelectedItem(p.getCommunity());
            }
        }
        if(s==0){
            JOptionPane.showMessageDialog(this ," NO RECORD FOUND ");
        }
        jNametxt.setEditable(false);
        jAgetxt.setEditable(false);
        jPhonenotxt.setEditable(false);
        jEmailidtxt.setEditable(false);
        jAddresstxt.setEditable(false);
        jMalebtn.setEnabled(false);
        jFemalebtn.setEnabled(false);
        jLgbtqbtn.setEnabled(false);
        jCommunitycmb.setEnabled(false);
        jCitycmb.setEnabled(false);
        /*String patient =jPersonidtxt.getText();
        Person p = new Person();
        for(Person per : person.getPerson()){
            if (String.valueOf(per.getPersonid()).equals(patient))
            {
                jNametxt.setText(p.getName());
                jAgetxt.setText(String.valueOf(p.getAge()));
                if (p.getGender().equals("Male"))
                {
                    //genderGroup.setSelected((ButtonModel) btnMale, true);
                    jMalebtn.setSelected(true);
                }
                else if (p.getGender().equals("Female"))
                {
                    //genderGroup.setSelected(btnF, true);
                    jFemalebtn.setSelected(true);
                }
                else
                {
                    jLgbtqbtn.setSelected(true);
                }
                jPhonenotxt.setText(String.valueOf(p.getPhoneno()));
                jEmailidtxt.setText(p.getEmailid());
                jAddresstxt.setText(p.getAddress());
                jCitycmb.setSelectedItem(p.getCity());  
                jCommunitycmb.setSelectedItem(p.getCommunity());
                break;
            }
        } */
    }//GEN-LAST:event_jSearchbtnActionPerformed

    private void jNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNametxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jNametxtKeyTyped

    private void jAgetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jAgetxtKeyTyped

    private void jPhonenotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhonenotxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jPhonenotxtKeyTyped

    private void jPIEditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPIEditbtnActionPerformed
        // TODO add your handling code here:
        jNametxt.setEditable(true);
        jAgetxt.setEditable(true);
        jPhonenotxt.setEditable(true);
        jEmailidtxt.setEditable(true);
        jAddresstxt.setEditable(true);
        jMalebtn.setEnabled(true);
        jFemalebtn.setEnabled(true);
        jLgbtqbtn.setEnabled(true);
        jCommunitycmb.setEnabled(true);
        jCitycmb.setEnabled(true);
    }//GEN-LAST:event_jPIEditbtnActionPerformed

    private void jPISavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPISavebtnActionPerformed
        // TODO add your handling code here:
        short checkName = 0;
        short checkAge = 0;
        short checkGender = 0;
        short checkPhoneno = 0;
        short checkEmailid = 0;
        short checkAddress = 0;
        short checkCommunity = 0;
        short checkCity = 0;
        if (jMalebtn.isSelected()) {
            g=1;
        }
        else if (jFemalebtn.isSelected()) {
            g=2;
        }
        else if (jLgbtqbtn.isSelected()) {
            g=3;
        }
        //short checkPersonUsername = 0;
        //short checkPersonPassword = 0;
        try{
            if (jNametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Name");
                jNametxt.setText("");
                checkName = 1;
            }
            if (jAgetxt.getText().isEmpty() && checkName==0){
                JOptionPane.showMessageDialog(null, "Please provide Age");
                jAgetxt.setText("");
                checkAge = 1;
            }
            if (g == 0 && checkName==0 && checkAge==0){
                JOptionPane.showMessageDialog(null, "Please provide Gender");
                checkGender = 1;
            }
            if (jPhonenotxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0){
                JOptionPane.showMessageDialog(null, "Please provide Phone Number");
                jPhonenotxt.setText("");
                checkPhoneno = 1;
            }
            if (jEmailidtxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0){
                JOptionPane.showMessageDialog(null, "Please provide Email ID");
                jEmailidtxt.setText("");
                checkEmailid = 1;
            }
            if (jAddresstxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0){
                JOptionPane.showMessageDialog(null, "Please provide Address");
                jAddresstxt.setText("");
                checkAddress = 1;
            }
            if (jCommunitycmb.getSelectedItem().toString().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0){
                JOptionPane.showMessageDialog(null, "Please provide Community");
                jCommunitycmb.setSelectedItem(null);
                checkCommunity = 1;
            }
            if (jCitycmb.getSelectedItem().toString().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0 && checkCommunity==0){
                JOptionPane.showMessageDialog(null, "Please provide City");
                jCitycmb.setSelectedItem(null);
                checkCity = 1;
            }
            /*if (jPersonUsernametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Username");
                jPersonUsernametxt.setText("");
                checkName = 1;
            }
            if (jPersonPasswordtxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Password");
                jPersonPasswordtxt.setText("");
                checkName = 1;
            }*/
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in provided Details");
                }
        if (checkCity==0 && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0 && checkCommunity==0){
                int personid = (Integer.parseInt(jPersonidtxt.getText()));
                String name = (jNametxt.getText());
                int age = (Integer.parseInt(jAgetxt.getText()));
                String gender;
                switch (g) {
                    case 1 -> gender = (jMalebtn.getText());
                    case 2 -> gender = (jFemalebtn.getText());
                    default -> gender = (jLgbtqbtn.getText());
                }
                long phoneno = (Long.parseLong(jPhonenotxt.getText()));
                String emailid = (jEmailidtxt.getText());
                String address = (jAddresstxt.getText());
                String community = (jCommunitycmb.getSelectedItem().toString());
                String city = (jCitycmb.getSelectedItem().toString());
                Person p = new Person(personid,name,age,gender,phoneno,emailid,address,city,community);
                JOptionPane.showMessageDialog(null, "Person Data Updated for Unique id :  "+personid);
                //PersonInfojPanel personinfo = new PersonInfojPanel(person,patient);
                //personinfo.setVisible(true);
                //setVisible(false);
        } else {
                JOptionPane.showMessageDialog(null, "Cannot Update Person, Please provide all the details");
        }   
        
        jNametxt.setEditable(false);
        jAgetxt.setEditable(false);
        jPhonenotxt.setEditable(false);
        jEmailidtxt.setEditable(false);
        jAddresstxt.setEditable(false);
        jMalebtn.setEnabled(false);
        jFemalebtn.setEnabled(false);
        jLgbtqbtn.setEnabled(false);
        jCommunitycmb.setEnabled(false);
        jCitycmb.setEnabled(false);
        
    }//GEN-LAST:event_jPISavebtnActionPerformed

    private void jRRatetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRRatetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jRRatetxtKeyTyped

    private void jPatienttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatienttxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jPatienttxtKeyTyped

    private void jHRatetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHRatetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jHRatetxtKeyTyped

    private void jDoctortxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDoctortxt1KeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jDoctortxt1KeyTyped

    private void jReadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadbtnActionPerformed
        // TODO add your handling code here:
        int selectedrow = jPEncountertbl.getSelectedRow();
        if (selectedrow < 0){
            JOptionPane.showMessageDialog(null, "please select");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jPEncountertbl.getModel();
        String patient = model.getValueAt(jPEncountertbl.getSelectedRow(),0).toString();
        String doctor = model.getValueAt(jPEncountertbl.getSelectedRow(),1).toString();
        String enc = model.getValueAt(jPEncountertbl.getSelectedRow(),2).toString();
        String rrate = model.getValueAt(jPEncountertbl.getSelectedRow(),3).toString();
        String hrrate = model.getValueAt(jPEncountertbl.getSelectedRow(),4).toString();
        String height = model.getValueAt(jPEncountertbl.getSelectedRow(),5).toString();
        String weight = model.getValueAt(jPEncountertbl.getSelectedRow(),6).toString();
        String abnormal = model.getValueAt(jPEncountertbl.getSelectedRow(),7).toString();

        jPatienttxt.setText(patient);
        jDoctortxt1.setText(doctor);
        jEncountertxt.setText(enc);
        jRRatetxt.setText(rrate);
        jHRatetxt.setText(hrrate);
        jHeighttxt.setText(height);
        jWeighttxt.setText(weight);
        jAbnormaltxt.setSelectedItem(abnormal);
    }//GEN-LAST:event_jReadbtnActionPerformed

    private void jHeighttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHeighttxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jHeighttxtKeyTyped

    private void jWeighttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jWeighttxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jWeighttxtKeyTyped

    private void loadComboBoxData(){
        jCitycmb.removeAllItems();
        jCommunitycmb.removeAllItems();
        for(City city: SystemHospitaljPanel.cityList){
            jCitycmb.addItem(city.getCityName());
        }
        for(City city:SystemHospitaljPanel.cityList){
            jCommunitycmb.addItem(city.getCommunity());
        }
        for(City city: HospitalAdminHospitaljPanel.cityList){
            jCitycmb.addItem(city.getCityName());
        }
        for(City city: HospitalAdminHospitaljPanel.cityList){
            jCommunitycmb.addItem(city.getCommunity());
        }
        jCitycmb.setSelectedIndex(-1);
        jCommunitycmb.setSelectedIndex(-1);
    }
    
    private void populateDocTable() {
    DefaultTableModel model = (DefaultTableModel) jDoctorComtbl.getModel();
    model.setRowCount(0);
    
    for(Doctor doc:perform.getDoctors())
    {
        Object[] row =new Object[2];
        row[0] =doc.getDoctorName();
        row[1] =doc.getHospital();

        model.addRow(row);
    }
    }
    private void populateEncTable() {
        
        DefaultTableModel model = (DefaultTableModel) jPEncountertbl.getModel();
        model.setRowCount(0);
        
        for (Encounter pd : ehistory.getEncounterHistory()){
          
            Object[] row = new Object[8];
            row[0] = pd.getPersonid();
            row[1] = pd.getDoctorName();
            row[2] = pd.getEncounter();
            row[3] = pd.getVital().getRespirationRate();
            row[4] = pd.getVital().getHeartRate();
            row[5] = pd.getVital().getHeight();
            row[6] = pd.getVital().getWeight();
            row[7] = pd.getVital().isAbnormal();
            
            model.addRow(row);

        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDetailsjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDetailsjFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAbnormallbl;
    private javax.swing.JComboBox<String> jAbnormaltxt;
    private javax.swing.JLabel jAddresslbl;
    private javax.swing.JTextField jAddresstxt;
    private javax.swing.JLabel jAgelbl;
    private javax.swing.JTextField jAgetxt;
    private javax.swing.JButton jBackbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCitycmb;
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JComboBox<String> jCommunitycmb;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JButton jDCReadbtn;
    private javax.swing.JScrollPane jDoctorComPane;
    private javax.swing.JTable jDoctorComtbl;
    private javax.swing.JLabel jDoctorcomHeading;
    private javax.swing.JLabel jDoctorlbl;
    private javax.swing.JLabel jDoctorlbl1;
    private javax.swing.JTextField jDoctortxt;
    private javax.swing.JTextField jDoctortxt1;
    private javax.swing.JLabel jEmailidlbl;
    private javax.swing.JTextField jEmailidtxt;
    private javax.swing.JLabel jEncountersHeading;
    private javax.swing.JTextField jEncountertxt;
    private javax.swing.JRadioButton jFemalebtn;
    private javax.swing.ButtonGroup jGenderbtngrp;
    private javax.swing.JLabel jGenderlbl;
    private javax.swing.JLabel jHRatelbl;
    private javax.swing.JTextField jHRatetxt;
    private javax.swing.JLabel jHeightlbl;
    private javax.swing.JTextField jHeighttxt;
    private javax.swing.JLabel jHospitallbl;
    private javax.swing.JTextField jHospitaltxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jLgbtqbtn;
    private javax.swing.JButton jLogoutbtn;
    private javax.swing.JRadioButton jMalebtn;
    private javax.swing.JLabel jNamelbl;
    private javax.swing.JTextField jNametxt;
    private javax.swing.JScrollPane jPEncounterPane;
    private javax.swing.JTable jPEncountertbl;
    private javax.swing.JButton jPIEditbtn;
    private javax.swing.JButton jPISavebtn;
    private javax.swing.JLabel jPatientHeading;
    private javax.swing.JLabel jPatientlbl;
    private javax.swing.JTextField jPatienttxt;
    private javax.swing.JLabel jPersonidlbl;
    private javax.swing.JTextField jPersonidtxt;
    private javax.swing.JLabel jPhonenolbl;
    private javax.swing.JTextField jPhonenotxt;
    private javax.swing.JLabel jRRatelbl;
    private javax.swing.JTextField jRRatetxt;
    private javax.swing.JButton jReadbtn;
    private javax.swing.JButton jSearchbtn;
    private javax.swing.JLabel jWeightlbl;
    private javax.swing.JTextField jWeighttxt;
    // End of variables declaration//GEN-END:variables
}
