/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Source.Patient;
import Source.PatientDirectory;
import Source.Person;
import Source.PersonDirectory;
import java.util.ArrayList;

/**
 *
 * @author srikr
 */
public class PersonInfojPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonInfojPanel
     */
    PersonDirectory person;
    PatientDirectory patient;
    ArrayList<Person> personList;
    ArrayList<Patient> patientList;
    public PersonInfojPanel(PersonDirectory person,PatientDirectory patient) {
        initComponents();
        this.person = person;
        this.personList = person.getPerson();
        this.patient = patient;
        this.patientList = patient.getPatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenderbtngrp = new javax.swing.ButtonGroup();
        jEmailidlbl = new javax.swing.JLabel();
        jGenderlbl = new javax.swing.JLabel();
        jNamelbl = new javax.swing.JLabel();
        jAgelbl = new javax.swing.JLabel();
        jCommunitylbl = new javax.swing.JLabel();
        jCitylbl = new javax.swing.JLabel();
        jAddresslbl = new javax.swing.JLabel();
        jPhonenolbl = new javax.swing.JLabel();
        jHeading = new javax.swing.JLabel();
        jPersonidlbl = new javax.swing.JLabel();
        jPersonidtxt = new javax.swing.JTextField();
        jNametxt = new javax.swing.JTextField();
        jAgetxt = new javax.swing.JTextField();
        jPhonenotxt = new javax.swing.JTextField();
        jEmailidtxt = new javax.swing.JTextField();
        jAddresstxt = new javax.swing.JTextField();
        jCommunitytxt = new javax.swing.JTextField();
        jCitytxt = new javax.swing.JTextField();
        jMalebtn = new javax.swing.JRadioButton();
        jFemalebtn = new javax.swing.JRadioButton();
        jLgbtqbtn = new javax.swing.JRadioButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jEmailidlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jEmailidlbl.setText("Email ID :");

        jGenderlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jGenderlbl.setText("Gender :");

        jNamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jNamelbl.setText("Name :");

        jAgelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAgelbl.setText("Age :");

        jCommunitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCommunitylbl.setText("Community :");

        jCitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCitylbl.setText("City :");

        jAddresslbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAddresslbl.setText("Address :");

        jPhonenolbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPhonenolbl.setText("Phone Number :");

        jHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jHeading.setText("PERSON INFORMATION");

        jPersonidlbl.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jPersonidlbl.setText("PERSON UNIQUE ID :");

        jPersonidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPersonidtxtActionPerformed(evt);
            }
        });

        jAgetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgetxtActionPerformed(evt);
            }
        });

        jGenderbtngrp.add(jMalebtn);
        jMalebtn.setText("Male");

        jGenderbtngrp.add(jFemalebtn);
        jFemalebtn.setText("Female");

        jGenderbtngrp.add(jLgbtqbtn);
        jLgbtqbtn.setText("LGBTQ+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(477, 477, 477))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPhonenolbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPersonidlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEmailidlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jGenderlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNamelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAgelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCommunitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAddresslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCommunitytxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAddresstxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jEmailidtxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPhonenotxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAgetxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jNametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(jPersonidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMalebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFemalebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLgbtqbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jNametxt, jPersonidtxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPersonidlbl)
                            .addComponent(jPersonidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAgelbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jGenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMalebtn)
                                    .addComponent(jFemalebtn)
                                    .addComponent(jLgbtqbtn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPhonenolbl)))
                            .addComponent(jNamelbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmailidlbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddresslbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCommunitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCommunitylbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCitylbl))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPersonidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPersonidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPersonidtxtActionPerformed

    private void jAgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgetxtActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jPersonidtxt.setText("");
        jNametxt.setText("");
        jAgetxt.setText("");
        jPhonenotxt.setText("");
        jEmailidtxt.setText("");
        jAddresstxt.setText("");
        jCommunitytxt.setText("");
        jCitytxt.setText("");
        
        jPersonidtxt.setEditable(false);
        jNametxt.setEditable(false);
        jAgetxt.setEditable(false);
        jPhonenotxt.setEditable(false);
        jEmailidtxt.setEditable(false);
        jAddresstxt.setEditable(false);
        jCommunitytxt.setEditable(false);
        jCitytxt.setEditable(false);
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddresslbl;
    private javax.swing.JTextField jAddresstxt;
    private javax.swing.JLabel jAgelbl;
    private javax.swing.JTextField jAgetxt;
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JTextField jCitytxt;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JTextField jCommunitytxt;
    private javax.swing.JLabel jEmailidlbl;
    private javax.swing.JTextField jEmailidtxt;
    private javax.swing.JRadioButton jFemalebtn;
    private javax.swing.ButtonGroup jGenderbtngrp;
    private javax.swing.JLabel jGenderlbl;
    private javax.swing.JLabel jHeading;
    private javax.swing.JRadioButton jLgbtqbtn;
    private javax.swing.JRadioButton jMalebtn;
    private javax.swing.JLabel jNamelbl;
    private javax.swing.JTextField jNametxt;
    private javax.swing.JLabel jPersonidlbl;
    private javax.swing.JTextField jPersonidtxt;
    private javax.swing.JLabel jPhonenolbl;
    private javax.swing.JTextField jPhonenotxt;
    // End of variables declaration//GEN-END:variables
}
