/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import javax.swing.JOptionPane;
import Source.*;
import Source.Person;
import Source.Patient;
import Source.PersonDirectory;;
import Source.PatientDirectory;
import java.util.ArrayList;
import Source.PatientDirectory;
import javax.swing.table.DefaultTableModel;
import Source.PatientDirectory;
import java.util.ArrayList;
import Source.PatientDirectory;

/**
 *
 * @author srikr
 */
public class PersonjPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonjPanel
     */
    PersonDirectory person;
    PatientDirectory patient;
    ArrayList<Person> personList;
    ArrayList<Patient> patientList;
    public PersonjPanel(PersonDirectory person,PatientDirectory patient) {
        initComponents();
        this.person = person;
        this.personList = person.getPerson();
        this.patient = patient;
        this.patientList = patient.getPatient();
    }

    private void clearFields(){
        jNametxt.setText(null);
        jAgetxt.setText(null);
        jCitytxt.setText(null);
        jCommunitytxt.setText(null);
        jAddresstxt.setText(null);
        jPersonUsernametxt.setText(null);
        jPersonPasswordtxt.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeading = new javax.swing.JLabel();
        jNamelbl = new javax.swing.JLabel();
        jAgelbl = new javax.swing.JLabel();
        jCommunitylbl = new javax.swing.JLabel();
        jCitylbl = new javax.swing.JLabel();
        jAddresslbl = new javax.swing.JLabel();
        jNametxt = new javax.swing.JTextField();
        jAgetxt = new javax.swing.JTextField();
        jAddresstxt = new javax.swing.JTextField();
        jCommunitytxt = new javax.swing.JTextField();
        jCitytxt = new javax.swing.JTextField();
        jCreatebtn = new javax.swing.JButton();
        jClearbtn = new javax.swing.JButton();
        jPersonUsernamelbl = new javax.swing.JLabel();
        jPersonPasswordlbl = new javax.swing.JLabel();
        jPersonUsernametxt = new javax.swing.JTextField();
        jPersonPasswordtxt = new javax.swing.JPasswordField();

        jHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jHeading.setText("PERSON INFORMATION");

        jNamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jNamelbl.setText("Name :");

        jAgelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAgelbl.setText("Age :");

        jCommunitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCommunitylbl.setText("Community :");

        jCitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCitylbl.setText("City :");

        jAddresslbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAddresslbl.setText("Address :");

        jNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNametxtActionPerformed(evt);
            }
        });
        jNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNametxtKeyTyped(evt);
            }
        });

        jAgetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgetxtActionPerformed(evt);
            }
        });
        jAgetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAgetxtKeyTyped(evt);
            }
        });

        jCommunitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCommunitytxtKeyTyped(evt);
            }
        });

        jCitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCitytxtKeyTyped(evt);
            }
        });

        jCreatebtn.setText("CREATE");
        jCreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreatebtnActionPerformed(evt);
            }
        });

        jClearbtn.setText("CLEAR");
        jClearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearbtnActionPerformed(evt);
            }
        });

        jPersonUsernamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPersonUsernamelbl.setText("Person Username");

        jPersonPasswordlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPersonPasswordlbl.setText("Person Password :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCreatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(jClearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jAddresslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCitylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCommunitylbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(jAgelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPersonPasswordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPersonUsernamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAgetxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNametxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jAddresstxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCommunitytxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCitytxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPersonUsernametxt)
                            .addComponent(jPersonPasswordtxt))))
                .addGap(424, 424, 424))
            .addGroup(layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(368, 368, 368))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamelbl)
                    .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgelbl)
                    .addComponent(jAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddresslbl)
                    .addComponent(jAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCommunitylbl)
                    .addComponent(jCommunitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCitylbl)
                    .addComponent(jCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPersonUsernamelbl)
                    .addComponent(jPersonUsernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPersonPasswordlbl)
                    .addComponent(jPersonPasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreatebtn)
                    .addComponent(jClearbtn))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAddresslbl, jAgelbl, jCitylbl, jCommunitylbl, jNamelbl});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAddresstxt, jAgetxt, jCitytxt, jCommunitytxt, jNametxt});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jClearbtn, jCreatebtn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPersonPasswordtxt, jPersonUsernametxt});

    }// </editor-fold>//GEN-END:initComponents

    private void jNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNametxtActionPerformed

    private void jAgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgetxtActionPerformed

    private void jClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearbtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jClearbtnActionPerformed

    private void jNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNametxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jNametxtKeyTyped

    private void jCitytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCitytxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jCitytxtKeyTyped

    private void jAgetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jAgetxtKeyTyped

    private void jCommunitytxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommunitytxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jCommunitytxtKeyTyped

    private void jCreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreatebtnActionPerformed
        // TODO add your handling code here:
        short checkName = 0;
        short checkAge = 0;
        short checkAddress = 0;
        short checkCommunity = 0;
        short checkCity = 0;
        short checkPersonUsername = 0;
        short checkPersonPassword = 0;
        try{
            if (jNametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Name");
                jNametxt.setText("");
                checkName = 1;
            }
            if (jAgetxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Age");
                jAgetxt.setText("");
                checkAge = 1;
            }
            if (jAddresstxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Address");
                jAddresstxt.setText("");
                checkAddress = 1;
            }
            if (jCommunitytxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Community");
                jCommunitytxt.setText("");
                checkCommunity = 1;
            }
            if (jCitytxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide City");
                jCitytxt.setText("");
                checkCity = 1;
            }
            if (jPersonUsernametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Username");
                jPersonUsernametxt.setText("");
                checkName = 1;
            }
            if (jPersonPasswordtxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Password");
                jPersonPasswordtxt.setText("");
                checkName = 1;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in provided Details");
                }
        if (((checkName == 0) && (checkAge == 0) && (checkAddress == 0) && (checkCommunity == 0) && (checkCity == 0))){
                Person pr = person.addNewPersonDetails();
                pr.setName(jNametxt.getText());
                pr.setAge(Integer.parseInt(jAgetxt.getText()));
                pr.setAddress(jAddresstxt.getText());
                pr.setCommunityName(jCommunitytxt.getText());
                pr.setCityName(jCitytxt.getText());
                JOptionPane.showMessageDialog(null, "Person Created");
                clearFields();
        } else {
                JOptionPane.showMessageDialog(null, "Cannot Create Person, Please provide all the details");
        }   
        
    }//GEN-LAST:event_jCreatebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddresslbl;
    private javax.swing.JTextField jAddresstxt;
    private javax.swing.JLabel jAgelbl;
    private javax.swing.JTextField jAgetxt;
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JTextField jCitytxt;
    private javax.swing.JButton jClearbtn;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JTextField jCommunitytxt;
    private javax.swing.JButton jCreatebtn;
    private javax.swing.JLabel jHeading;
    private javax.swing.JLabel jNamelbl;
    private javax.swing.JTextField jNametxt;
    private javax.swing.JLabel jPersonPasswordlbl;
    private javax.swing.JPasswordField jPersonPasswordtxt;
    private javax.swing.JLabel jPersonUsernamelbl;
    private javax.swing.JTextField jPersonUsernametxt;
    // End of variables declaration//GEN-END:variables
}
