/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import javax.swing.JOptionPane;
import Source.*;
import Source.Person;
import Source.Patient;
import Source.PersonDirectory;;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import Source.PatientDirectory;

/**
 *
 * @author srikr
 */
public class PersonjPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonjPanel
     */
    PersonDirectory person;
    PatientDirectory patient;
    ArrayList<Person> personList;
    ArrayList<Patient> patientList;
    int g=0;
    public PersonjPanel(PersonDirectory person,PatientDirectory patient) {
        initComponents();
        this.person = person;
        this.personList = person.getPerson();
        this.patient = patient;
        this.patientList = patient.getPatient();
        loadComboBoxData();
    }

    private void clearFields(){
        jNametxt.setText(null);
        jAgetxt.setText(null);
        jCitytxt.setSelectedItem(null);
        jCommunitytxt.setSelectedItem(null);
        jAddresstxt.setText(null);
        jMale.setSelected(false);
        jFemale.setSelected(false);
        jLgbtq.setSelected(false);
        jGenderbtngrp.clearSelection();
        jPhonenotxt.setText(null);
        jEmailidtxt.setText(null);
        //jPersonUsernametxt.setText(null);
        //jPersonPasswordtxt.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGenderbtngrp = new javax.swing.ButtonGroup();
        jHeading = new javax.swing.JLabel();
        jNamelbl = new javax.swing.JLabel();
        jAgelbl = new javax.swing.JLabel();
        jCommunitylbl = new javax.swing.JLabel();
        jCitylbl = new javax.swing.JLabel();
        jAddresslbl = new javax.swing.JLabel();
        jNametxt = new javax.swing.JTextField();
        jAgetxt = new javax.swing.JTextField();
        jAddresstxt = new javax.swing.JTextField();
        jCreatebtn = new javax.swing.JButton();
        jClearbtn = new javax.swing.JButton();
        jGenderlbl = new javax.swing.JLabel();
        jMale = new javax.swing.JRadioButton();
        jFemale = new javax.swing.JRadioButton();
        jLgbtq = new javax.swing.JRadioButton();
        jPhonenolbl = new javax.swing.JLabel();
        jPhonenotxt = new javax.swing.JTextField();
        jEmailidlbl = new javax.swing.JLabel();
        jEmailidtxt = new javax.swing.JTextField();
        jCommunitytxt = new javax.swing.JComboBox<>();
        jCitytxt = new javax.swing.JComboBox<>();

        setToolTipText("");

        jHeading.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jHeading.setText("PERSON REGISTRATION");

        jNamelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jNamelbl.setText("Name :");

        jAgelbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAgelbl.setText("Age :");

        jCommunitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCommunitylbl.setText("Community :");

        jCitylbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCitylbl.setText("City :");

        jAddresslbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jAddresslbl.setText("Address :");

        jNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNametxtActionPerformed(evt);
            }
        });
        jNametxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNametxtKeyTyped(evt);
            }
        });

        jAgetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgetxtActionPerformed(evt);
            }
        });
        jAgetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAgetxtKeyTyped(evt);
            }
        });

        jCreatebtn.setBackground(new java.awt.Color(255, 204, 51));
        jCreatebtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jCreatebtn.setText("CREATE");
        jCreatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreatebtnActionPerformed(evt);
            }
        });

        jClearbtn.setBackground(new java.awt.Color(255, 204, 51));
        jClearbtn.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jClearbtn.setText("CLEAR");
        jClearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearbtnActionPerformed(evt);
            }
        });

        jGenderlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jGenderlbl.setText("Gender :");

        jGenderbtngrp.add(jMale);
        jMale.setText("Male");
        jMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaleActionPerformed(evt);
            }
        });

        jGenderbtngrp.add(jFemale);
        jFemale.setText("Female");
        jFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFemaleActionPerformed(evt);
            }
        });

        jGenderbtngrp.add(jLgbtq);
        jLgbtq.setText("LGBTQ+");
        jLgbtq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLgbtqActionPerformed(evt);
            }
        });

        jPhonenolbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jPhonenolbl.setText("Phone Number :");

        jPhonenotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPhonenotxtKeyTyped(evt);
            }
        });

        jEmailidlbl.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jEmailidlbl.setText("Email ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jHeading)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCreatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jClearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jAddresslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCitylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCommunitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jEmailidlbl)
                                    .addComponent(jPhonenolbl)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jAgelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jNamelbl))
                                    .addComponent(jGenderlbl))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNametxt)
                                    .addComponent(jAgetxt)
                                    .addComponent(jPhonenotxt)
                                    .addComponent(jEmailidtxt)
                                    .addComponent(jAddresstxt, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFemale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLgbtq))
                                    .addComponent(jCommunitytxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCitytxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(139, 139, 139))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAddresstxt, jCommunitytxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNamelbl)
                    .addComponent(jNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgelbl)
                    .addComponent(jAgetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMale)
                    .addComponent(jFemale)
                    .addComponent(jLgbtq))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhonenolbl)
                    .addComponent(jPhonenotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmailidlbl)
                    .addComponent(jEmailidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddresslbl)
                    .addComponent(jAddresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCommunitylbl)
                    .addComponent(jCommunitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCitylbl)
                    .addComponent(jCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClearbtn))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAddresslbl, jAgelbl, jCitylbl, jCommunitylbl, jNamelbl});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jAddresstxt, jAgetxt, jCommunitytxt, jNametxt});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jClearbtn, jCreatebtn});

    }// </editor-fold>//GEN-END:initComponents

    private void jNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNametxtActionPerformed

    private void jAgetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgetxtActionPerformed

    private void jClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearbtnActionPerformed
        // TODO add your handling code here:
        clearFields();
        g=0;
    }//GEN-LAST:event_jClearbtnActionPerformed

    private void jNametxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNametxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isAlphabetic(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jNametxtKeyTyped

    private void jAgetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgetxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jAgetxtKeyTyped

    private void jCreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreatebtnActionPerformed
        // TODO add your handling code here:
        short checkName = 0;
        short checkAge = 0;
        short checkGender = 0;
        short checkPhoneno = 0;
        short checkEmailid = 0;
        short checkAddress = 0;
        short checkCommunity = 0;
        short checkCity = 0;
        //short checkPersonUsername = 0;
        //short checkPersonPassword = 0;
        try{
            if (jNametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Name");
                jNametxt.setText("");
                checkName = 1;
            }
            if (jAgetxt.getText().isEmpty() && checkName==0){
                JOptionPane.showMessageDialog(null, "Please provide Age");
                jAgetxt.setText("");
                checkAge = 1;
            }
            if (g == 0 && checkName==0 && checkAge==0){
                JOptionPane.showMessageDialog(null, "Please provide Gender");
                checkGender = 1;
            }
            if (jPhonenotxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0){
                JOptionPane.showMessageDialog(null, "Please provide Phone Number");
                jPhonenotxt.setText("");
                checkPhoneno = 1;
            }
            if (jEmailidtxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0){
                JOptionPane.showMessageDialog(null, "Please provide Email ID");
                jEmailidtxt.setText("");
                checkEmailid = 1;
            }
            if (jAddresstxt.getText().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0){
                JOptionPane.showMessageDialog(null, "Please provide Address");
                jAddresstxt.setText("");
                checkAddress = 1;
            }
            if (jCommunitytxt.getSelectedItem().toString().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0){
                JOptionPane.showMessageDialog(null, "Please provide Community");
                jCommunitytxt.setSelectedItem(null);
                checkCommunity = 1;
            }
            if (jCitytxt.getSelectedItem().toString().isEmpty() && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0 && checkCommunity==0){
                JOptionPane.showMessageDialog(null, "Please provide City");
                jCitytxt.setSelectedItem(null);
                checkCity = 1;
            }
            /*if (jPersonUsernametxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Username");
                jPersonUsernametxt.setText("");
                checkName = 1;
            }
            if (jPersonPasswordtxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please provide Person Password");
                jPersonPasswordtxt.setText("");
                checkName = 1;
            }*/
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in provided Details");
                }
        if (checkCity==0 && checkGender==0 && checkName==0 && checkAge==0 
                    && checkPhoneno==0 && checkEmailid==0 && checkAddress==0 && checkCommunity==0){
                Person pr = person.addNewPersonDetails();
                pr.setName(jNametxt.getText());
                pr.setAge(Integer.parseInt(jAgetxt.getText()));
                switch (g) {
                    case 1 -> pr.setGender(jMale.getText());
                    case 2 -> pr.setGender(jFemale.getText());
                    default -> pr.setGender(jLgbtq.getText());
                }
                g=0;
                pr.setPhoneno(Long.parseLong(jPhonenotxt.getText()));
                pr.setEmailid(jEmailidtxt.getText());
                pr.setAddress(jAddresstxt.getText());
                pr.setCommunity(jCommunitytxt.getSelectedItem().toString());
                pr.setCity(jCitytxt.getSelectedItem().toString());
                PersonDirectory.getPerson().add(pr);
                JOptionPane.showMessageDialog(null, "Person Created, Your Unique id is :  "+pr.getPersonid()+"\nPlease use your Unique id as PATIENT USERNAME and PATIENT PASSWORD.");
                clearFields();
                //PersonInfojPanel personinfo = new PersonInfojPanel(person,patient);
                //personinfo.setVisible(true);
                //setVisible(false);
        } else {
                JOptionPane.showMessageDialog(null, "Cannot Create Person, Please provide all the details");
        }   
        
    }//GEN-LAST:event_jCreatebtnActionPerformed

    private void jMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaleActionPerformed
        // TODO add your handling code here:
        if (jMale.isSelected()) {
            g=1;
        }
    }//GEN-LAST:event_jMaleActionPerformed

    private void jLgbtqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLgbtqActionPerformed
        // TODO add your handling code here:
        if (jLgbtq.isSelected()) {
            g=3;
        }
    }//GEN-LAST:event_jLgbtqActionPerformed

    private void jPhonenotxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhonenotxtKeyTyped
        // TODO add your handling code here:
        char value = evt.getKeyChar();
        if((!Character.isDigit(value))){
            evt.consume();
        }
    }//GEN-LAST:event_jPhonenotxtKeyTyped

    private void jFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFemaleActionPerformed
        // TODO add your handling code here:
        if (jFemale.isSelected()) {
            g=2;
        }
    }//GEN-LAST:event_jFemaleActionPerformed

    private void loadComboBoxData(){
        jCommunitytxt.removeAllItems();
        jCitytxt.removeAllItems();
        for(City city: SystemHospitaljPanel.cityList){
            jCitytxt.addItem(city.getCityName());
        }
        for(City city:SystemHospitaljPanel.cityList){
            jCommunitytxt.addItem(city.getCommunity());
        }
        for(City city: HospitalAdminHospitaljPanel.cityList){
            jCitytxt.addItem(city.getCityName());
        }
        for(City city: HospitalAdminHospitaljPanel.cityList){
            jCommunitytxt.addItem(city.getCommunity());
        }
        jCommunitytxt.setSelectedIndex(-1);
        jCitytxt.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddresslbl;
    private javax.swing.JTextField jAddresstxt;
    private javax.swing.JLabel jAgelbl;
    private javax.swing.JTextField jAgetxt;
    private javax.swing.JLabel jCitylbl;
    private javax.swing.JComboBox<String> jCitytxt;
    private javax.swing.JButton jClearbtn;
    private javax.swing.JLabel jCommunitylbl;
    private javax.swing.JComboBox<String> jCommunitytxt;
    private javax.swing.JButton jCreatebtn;
    private javax.swing.JLabel jEmailidlbl;
    private javax.swing.JTextField jEmailidtxt;
    private javax.swing.JRadioButton jFemale;
    private javax.swing.ButtonGroup jGenderbtngrp;
    private javax.swing.JLabel jGenderlbl;
    private javax.swing.JLabel jHeading;
    private javax.swing.JRadioButton jLgbtq;
    private javax.swing.JRadioButton jMale;
    private javax.swing.JLabel jNamelbl;
    private javax.swing.JTextField jNametxt;
    private javax.swing.JLabel jPhonenolbl;
    private javax.swing.JTextField jPhonenotxt;
    // End of variables declaration//GEN-END:variables
}
