/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author srikr
 */
public class SystemHospitaljPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemHospitaljPanel
     */
    public SystemHospitaljPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCreatebtn = new javax.swing.JButton();
        jReadbtn = new javax.swing.JButton();
        jUpdatebtn = new javax.swing.JButton();
        jHospitaldetailslbl = new javax.swing.JLabel();
        jHScrollPane = new javax.swing.JScrollPane();
        jHospitaltbl = new javax.swing.JTable();
        jDeletebtn = new javax.swing.JButton();

        jCreatebtn.setText("CREATE");

        jReadbtn.setText("READ");

        jUpdatebtn.setText("UPDATE");

        jHospitaldetailslbl.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jHospitaldetailslbl.setText("HOSPITAL DETAILS :");

        jHospitaltbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Community", "City"
            }
        ));
        jHScrollPane.setViewportView(jHospitaltbl);

        jDeletebtn.setText("DELETE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCreatebtn)
                                .addGap(30, 30, 30)
                                .addComponent(jReadbtn)
                                .addGap(30, 30, 30)
                                .addComponent(jUpdatebtn)
                                .addGap(30, 30, 30)
                                .addComponent(jDeletebtn))
                            .addComponent(jHospitaldetailslbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(356, 356, 356))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jHospitaldetailslbl)
                .addGap(12, 12, 12)
                .addComponent(jHScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreatebtn)
                    .addComponent(jReadbtn)
                    .addComponent(jUpdatebtn)
                    .addComponent(jDeletebtn))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCreatebtn;
    private javax.swing.JButton jDeletebtn;
    private javax.swing.JScrollPane jHScrollPane;
    private javax.swing.JLabel jHospitaldetailslbl;
    private javax.swing.JTable jHospitaltbl;
    private javax.swing.JButton jReadbtn;
    private javax.swing.JButton jUpdatebtn;
    // End of variables declaration//GEN-END:variables
}
